packages:
  - 'apps/*'
  - 'packages/*'

verifyDepsBeforeRun: never

onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - '@nestjs/core'
  - esbuild
  - '@swc/core'
  - '@prisma/client'
  - '@prisma/engines'
  - prisma
  - better-sqlite3

minimumReleaseAgeExclude:
  - '@typescript-eslint/eslint-plugin@8.60.0'
  - '@typescript-eslint/parser@8.60.0'
  - '@typescript-eslint/project-service@8.60.0'
  - '@typescript-eslint/scope-manager@8.60.0'
  - '@typescript-eslint/tsconfig-utils@8.60.0'
  - '@typescript-eslint/type-utils@8.60.0'
  - '@typescript-eslint/types@8.60.0'
  - '@typescript-eslint/typescript-estree@8.60.0'
  - '@typescript-eslint/utils@8.60.0'
  - '@typescript-eslint/visitor-keys@8.60.0'
  - typescript-eslint@8.60.0

allowBuilds:
  '@nestjs/core': set this to true or false
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  '@scarf/scarf': set this to true or false
  better-sqlite3: set this to true or false
  esbuild: set this to true or false
  prisma: set this to true or false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
